name: Lint Python

on:
  pull_request:

jobs:
  docker_lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Lint flows
        uses: gabriel-milan/action-pylint@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          path: "emd_flows/"
          fail: true
          pr-message: true
      - name: Lint tests
        uses: gabriel-milan/action-pylint@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          path: "tests/"
          fail: true
          pr-message: true
