name: Lint Python

on:
  pull_request:

jobs:
  docker_lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      - name: Set up Poetry and upgrade pip
        run: |
          pip install -U pip poetry
      - name: Install flows
        run: |
          pip install --prefer-binary .
      - name: Lint with flake8
        run: |
          flake8 pipelines/**/*.py