name: Lint Dockerfile

on:
  pull_request:

jobs:
  docker_lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
